//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.27703.1
// 
namespace IPDTracker.IPDTrackerServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillingEntry", Namespace="http://schemas.datacontract.org/2004/07/IPDTrackerService")]
    public partial class BillingEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime BillableDateField;
        
        private System.Guid BillableIdField;
        
        private System.TimeSpan BillableTimeField;
        
        private string ClientNameField;
        
        private string NotesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BillableDate {
            get {
                return this.BillableDateField;
            }
            set {
                if ((this.BillableDateField.Equals(value) != true)) {
                    this.BillableDateField = value;
                    this.RaisePropertyChanged("BillableDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BillableId {
            get {
                return this.BillableIdField;
            }
            set {
                if ((this.BillableIdField.Equals(value) != true)) {
                    this.BillableIdField = value;
                    this.RaisePropertyChanged("BillableId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan BillableTime {
            get {
                return this.BillableTimeField;
            }
            set {
                if ((this.BillableTimeField.Equals(value) != true)) {
                    this.BillableTimeField = value;
                    this.RaisePropertyChanged("BillableTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPDTrackerServiceReference.IIPDTrackerService")]
    public interface IIPDTrackerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPDTrackerService/GetEntries", ReplyAction="http://tempuri.org/IIPDTrackerService/GetEntriesResponse")]
        System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<IPDTracker.IPDTrackerServiceReference.BillingEntry>> GetEntriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPDTrackerService/GetEntry", ReplyAction="http://tempuri.org/IIPDTrackerService/GetEntryResponse")]
        System.Threading.Tasks.Task<IPDTracker.IPDTrackerServiceReference.BillingEntry> GetEntryAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPDTrackerService/DeleteEntry", ReplyAction="http://tempuri.org/IIPDTrackerService/DeleteEntryResponse")]
        System.Threading.Tasks.Task<bool> DeleteEntryAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPDTrackerService/UpdateEntry", ReplyAction="http://tempuri.org/IIPDTrackerService/UpdateEntryResponse")]
        System.Threading.Tasks.Task<bool> UpdateEntryAsync(IPDTracker.IPDTrackerServiceReference.BillingEntry entry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPDTrackerService/CreateEntry", ReplyAction="http://tempuri.org/IIPDTrackerService/CreateEntryResponse")]
        System.Threading.Tasks.Task<bool> CreateEntryAsync(IPDTracker.IPDTrackerServiceReference.BillingEntry entry);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIPDTrackerServiceChannel : IPDTracker.IPDTrackerServiceReference.IIPDTrackerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IPDTrackerServiceClient : System.ServiceModel.ClientBase<IPDTracker.IPDTrackerServiceReference.IIPDTrackerService>, IPDTracker.IPDTrackerServiceReference.IIPDTrackerService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IPDTrackerServiceClient() : 
                base(IPDTrackerServiceClient.GetDefaultBinding(), IPDTrackerServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IIPDTrackerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IPDTrackerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IPDTrackerServiceClient.GetBindingForEndpoint(endpointConfiguration), IPDTrackerServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IPDTrackerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IPDTrackerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IPDTrackerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IPDTrackerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IPDTrackerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.ObjectModel.ObservableCollection<IPDTracker.IPDTrackerServiceReference.BillingEntry>> GetEntriesAsync() {
            return base.Channel.GetEntriesAsync();
        }
        
        public System.Threading.Tasks.Task<IPDTracker.IPDTrackerServiceReference.BillingEntry> GetEntryAsync(System.Guid Id) {
            return base.Channel.GetEntryAsync(Id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEntryAsync(System.Guid Id) {
            return base.Channel.DeleteEntryAsync(Id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateEntryAsync(IPDTracker.IPDTrackerServiceReference.BillingEntry entry) {
            return base.Channel.UpdateEntryAsync(entry);
        }
        
        public System.Threading.Tasks.Task<bool> CreateEntryAsync(IPDTracker.IPDTrackerServiceReference.BillingEntry entry) {
            return base.Channel.CreateEntryAsync(entry);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIPDTrackerService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIPDTrackerService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:56102/IPDTrackerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return IPDTrackerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IIPDTrackerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return IPDTrackerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IIPDTrackerService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IIPDTrackerService,
        }
    }
}
